# This is a basic workflow to help you get started with Actions

name: Nextjs main CD

# Controls when the action will run. 
on:
  workflow_run:
    workflows:
      - Build Application CI
    types:
      - completed
    branches:
      - main
  workflow_dispatch:  # This allows the workflow to be manually triggered

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/apps/ProdMyFapSheetFrontend
          git pull
          git status
          npm install
          npm run build
          pm2 restart ProdMyFapSheetFrontend
          curl https://api.cloudflare.com/client/v4/zones/${{ secrets.ZONE_ID }}/purge_cache \
            -H 'Content-Type: application/json' \
            -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_EMAIL }}" \
            -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_API_KEY }}" \
            -d '{"purge_everything":true}'